### ISSUE TITLE
Can't install from SPM

### ISSUE THREAD

**Issue by Maxador** [pointfreeco/swift-html#1]
Output error:
```
error: the package PackageReference(identity: "swift-html", name: nil, path: "https://github.com/pointfreeco/swift-html.git", isLocal: false) @ 0.1.0 contains revisioned dependencies:
    PackageReference(identity: "swift-snapshot-testing", name: nil, path: "https://github.com/pointfreeco/swift-snapshot-testing.git", isLocal: false) @ 69b48c8
```

I guess it needs to use a version number tag for the `swift-snapshot-testing` dependency.

**Comment by mbrandonw** [comment]
Hey, thanks for trying out the lib!

And that's an error I've never seen before. Can you tell me what command you are running to get this?

We do use a revision specific dependency for `swift-snapshot-testing`, but it's only a test dependency so we feel ok doing that. We aren't yet ready to cut a 0.1 of that library.

Thanks!

**Comment by Maxador** [comment]
I was trying to add the library in a small `vapor` project with the `vapor update` command which is essentially use the `swift package update` command.

Swift 4.1.2 on macOS 10.13.6

Thank you for your great work (you and Stephen), I am really excited with this project!

**Comment by mbrandonw** [comment]
Huh, this is a new one to me, but I was able to reproduce. We use revision dependencies all the time and haven't come across this. I think it's because you're pointing to an exact version of swift-html, but inside there it's using a revision, which I guess that mismatch is prohibited.

Well, two things. 1) I'll just cut a 0.0.1 for `swift-snapshot-testing` so that it'll fix this issue. and 2) we just happen to be announcing this library http://github.com/pointfreeco/swift-html-vapor tomorrow, and it seems you may be interested in it. I'm just now working on the final touches.

I'll let you know when I've got the versions all fixed up...

**Comment by mbrandonw** [comment]
Oops didn't mean to close this issue with that PR.

But anyway, I've cut a 0.1.1 release. Can you give that a shot and let me know if it works?

**Comment by Maxador** [comment]
It downloaded without error. And I am really happy to see the vapor library is coming too!
It will probably need to reference the 0.1.1 release of this library now although.

**Comment by Maxador** [comment]
I have imported the library and it works perfectly fine.

**Comment by mbrandonw** [comment]
Beautiful! Let us know if you have any feedback, we'd love to hear it. We've been using this library for a year now, but would of course like to hear from a more diverse set of use cases.

Cheers!

**Comment by Maxador** [comment]
I will use it in my hobby project and will gladly provide feedback!

Cheers!
