### ISSUE TITLE
CSS dsl

### ISSUE THREAD

**Issue by marcocapano** [pointfreeco/swift-html#31]
Hello! Nice work with the library, I'm already working with it to create my personal website😊

From the playground:

> Some simple CSS for our page. This can be written right inline to our DSL, we could also load it from a file on disk, or better yet, we could create another DSL for modeling it 😉

I agree on this. Once you get used to modeling html this way, working with that multiline string css stylesheet feels even worse than before. It would also help people with more experience with swift but not with css, since it would provide autocompletion, compile safety and documentation within Xcode.

Now say I wanted to contribute and start working on it, is this library the good place for it or would you prefer a separate module?

**Comment by mbrandonw** [comment]
Hey @marcocapano! Yeah a separate module would be ideal so that people could pick and choose which framework they want to use (some people may want to use CSS with their own HTML library and vice versa).

If you haven't seen it already, we have a CSS DSL that we use to build www.pointfree.co. It's in our [swift-web](https://github.com/pointfreeco/swift-web) package, which is kind of our testbed for server-side libraries. In fact, the first version of this library began in swift-web and then we split it out into its own repo once it was refined enough. There's lots of tests in that repo to show how to use it (no docs unfortunately) and there's a ton of usage of it in the [pointfreeco](https://github.com/pointfreeco/pointfreeco/) repo.

Having said all of that, the more DSL's the better! If you create your own CSS DSL then it would be quite easy to build a helper function that allows you to use it with this library. You could just make a new `style` function that renders the CSS into a `<style>` tag. This is what we do for our CSS:

https://github.com/pointfreeco/swift-web/blob/0243fbe2a00ef81895b0671996e1b7fb0f8525bf/Sources/HtmlCssSupport/Support.swift#L16-L23

Cheers!

**Comment by mbrandonw** [comment]
Hey @marcocapano! We're going to close this for now. We definitely would love to introduce a new CSS DSL in the future, but it'll live in its own repository!
