### ISSUE TITLE
.div will take array literal but not an Array<Node>() instance

### ISSUE THREAD

**Issue by BryanJBryce** [pointfreeco/swift-html#56]
Mostly out of curiosity, I can work around this, but I'm not understanding why this works this way:

Here I can't pass an `Array<Node>`...
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/1293064/58210800-28f06c00-7c9f-11e9-843e-e0f65e8d27ea.png">

...but I _can_ pass an array literal

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/1293064/58210936-68b75380-7c9f-11e9-9b6a-de7c6a8d3bcd.png">

`Node` is an Enum, and one of its cases is `.fragment([Node])` so I see how the array literal works, but I don't understand why the `Array<Node>` instance doesn't.

**Comment by stephencelis** [comment]
Hi @BryanJBryce! The `div` function takes `Node...` as its second argument, and because `Node` is `ExpressibleByArrayLiteral`, it works when used as a literal. Because `div` does _not_ take `[Node]` as its second argument, if you're working with an explicit array you need to wrap them in `.fragment`.

``` swift
return .div(.fragment(definitions))
```

Note in the above example that the initial `[]` is no longer necessary to represent attributes. Attributes have an explicit label these days:

``` swift
return .div(attributes: [.class("headline")], .fragment(definitions))
```

Also note that you can omit the array literal entirely when building structures inline:

``` swift
return .div(.h1("flying"), .h1("taco"))
```

**Comment by BryanJBryce** [comment]
Excellent, thank you!

**Comment by lorenzofanchi-enpicom** [comment]
Just started writing Swift code; spent about an hour to find a way to splat arrays, when I could've found the answer right here...

**Comment by lorenzofanchi** [comment]
Just started writing Swift code; spent about an hour to find a way to splat arrays, when I could've found the answer right here... Thanks!

Maybe useful to add this to the README or FAQ?
